version: "3.9"

services:
#  app:
#    build: .
#    depends_on:
#      - db
#    ports:
#      - "8000:80"

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "Admin12345@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
     
