version: "3.9"

services:
#  app:
#    build: .
#    depends_on:
#      - db
#    ports:
#      - "8000:80"

  db:
    image: "mcr.microsoft.com/azure-sql-edge"
    volumes:
      - todo_mssql:/var/opt/mssql
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Admin1234@
    ports:
      - "1433:1433"
  
volumes:
  todo_mssql:
     
